name: octagon
description: "A Octagon Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.5
  equatable: ^2.0.5
  http:
  introduction_screen: ^3.0.2
  resize: ^1.0.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.0.0+2
  firebase_auth: ^4.12.1
  flutter_bloc: ^7.0.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
#  firebase_core_platform_interface: ^5.0.0
  cloud_firestore: ^4.3.1
  provider: ^6.0.2
  awesome_notifications: ^0.9.2
  permission_handler:
  country_picker: ^2.0.16
  pin_code_text_field: ^1.8.0
  firebase_analytics: ^10.4.2
  fluttertoast: ^8.1.1
  share_plus:
  inview_notifier_list:
  cached_network_image:
  flutter_svg: ^2.0.9
  chewie:
  animated_icon_button: ^1.0.2
  dotted_border: ^2.0.0+2
  flutter_icons_null_safety: ^1.1.0
  flutter_spinkit: ^5.0.0
  animations: ^2.0.0
  #  flutter_native_splash: ^1.3.1
  flutter_native_splash: ^2.2.16
  salomon_bottom_bar: ^3.3.0
  focused_menu: ^1.0.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.1
  video_player: ^2.4.10
  card_swiper: ^3.0.1
  story: ^1.1.0
  #  flutter_facebook_login: ^3.0.0
  #  image_picker: ^0.8.6
  #  photo_view: ^0.14.0
  image_editor_plus: ^1.0.6
  path_provider: ^2.0.11
  video_editor: ^2.4.0
  #  helpers: ^1.1.4
  webview_flutter: ^4.0.7
  #chat
  flutter_chat_ui: ^1.6.4
  uuid: ^4.3.3
  #  hexagon: ^0.1.1
  flutter_dash: ^1.0.0
  video_thumbnail: ^0.5.3
  custom_pop_up_menu: ^1.2.4
  shape_maker: ^0.0.1-dev.1
  firebase_remote_config: ^4.2.3
  package_info_plus: ^5.0.1
  open_store: ^0.5.0
  quick_actions: ^1.0.5
  socket_io_client: ^1.0.2
  jiffy: ^6.2.1
  lottie: ^3.1.2
  google_sign_in: ^6.1.5
  sizer: ^2.0.15
  app_links: ^6.3.3
  sign_in_with_apple: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/onBoarding/
    - assets/splash/
    - assets/json/
    - assets/ic/